### ISSUE TITLE
gimps drops the inline comments from imports

### ISSUE THREAD

**Issue by kron4eg** [xrstf/gimps#1]
Hello!

Been fan if this tools for a long time, keep it up, nicely done!

Please see the image attached for the issue:

![Screenshot from 2023-10-25 16-09-02](https://github.com/xrstf/gimps/assets/30984/c26890cb-9b9b-4aa9-973e-0c9433f4cbda)

**Comment by xrstf** [comment]
Thanks for the report, gimps indeed had issues dealing with directive-style comments, as they are handled a bit differently in Go. v0.6.0 should fix the issue.
